"""create coupon tables

Revision ID: 4a5022ef3817
Revises: 164ce801f620
Create Date: 2026-09-22 07:31:19.171729

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '4a5022ef3817'
down_revision: str | None = '164ce801f620'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_type', sa.Enum('percent', 'fixed', name='discount_type', native_enum=False), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('min_purchase', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('max_uses_per_user', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_index(op.f('ix_coupons_store_id'), 'coupons', ['store_id'], unique=False)
    op.create_table('coupon_redemptions',
    sa.Column('coupon_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coupon_id', 'order_id', name='uq_coupon_order')
    )
    op.create_index(op.f('ix_coupon_redemptions_coupon_id'), 'coupon_redemptions', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_coupon_redemptions_order_id'), 'coupon_redemptions', ['order_id'], unique=False)
    op.create_index(op.f('ix_coupon_redemptions_user_id'), 'coupon_redemptions', ['user_id'], unique=False)
    op.add_column('orders', sa.Column('discount_total', sa.Numeric(precision=12, scale=2), nullable=False))
    # Red de seguridad: Alembic no ve los índices GIN de búsqueda de products
    # (se crean con SQL crudo en 26a56be90086) y los marca como "sobrantes".
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_products_title_trgm ON products "
        "USING gin (title gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_products_search_vector ON products USING gin ("
        "to_tsvector('simple', coalesce(title, '') || ' ' || "
        "coalesce(description, '') || ' ' || coalesce(brand, ''))"
        ")"
    )
    # (por eso NO se elimina aquí ningún índice de products)
    op.add_column('seller_orders', sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller_orders', 'discount_amount')
    # (el downgrade no toca los índices GIN de búsqueda de products:
    #  los gestiona la migración 26a56be90086)
    op.drop_column('orders', 'discount_total')
    op.drop_index(op.f('ix_coupon_redemptions_user_id'), table_name='coupon_redemptions')
    op.drop_index(op.f('ix_coupon_redemptions_order_id'), table_name='coupon_redemptions')
    op.drop_index(op.f('ix_coupon_redemptions_coupon_id'), table_name='coupon_redemptions')
    op.drop_table('coupon_redemptions')
    op.drop_index(op.f('ix_coupons_store_id'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    # ### end Alembic commands ###
