"""create payment tables

Revision ID: b5bdd281b2fc
Revises: b6d53d444b30
Create Date: 2026-09-22 07:07:59.466048

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5bdd281b2fc'
down_revision: str | None = 'b6d53d444b30'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_reference', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'succeeded', 'failed', 'cancelled', 'refunded', name='payment_attempt_status', native_enum=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('checkout_url', sa.String(length=500), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'idempotency_key', name='uq_payment_idempotency')
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_provider_reference'), 'payments', ['provider_reference'], unique=True)
    op.create_table('payment_events',
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_event_id', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_payment_event')
    )
    op.create_index(op.f('ix_payment_events_payment_id'), 'payment_events', ['payment_id'], unique=False)
    # Red de seguridad: Alembic no ve los índices GIN de búsqueda de products
    # (se crean con SQL crudo en 26a56be90086) y los marca como "sobrantes".
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_products_title_trgm ON products "
        "USING gin (title gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_products_search_vector ON products USING gin ("
        "to_tsvector('simple', coalesce(title, '') || ' ' || "
        "coalesce(description, '') || ' ' || coalesce(brand, ''))"
        ")"
    )
    # (por eso NO se elimina aquí ningún índice de products)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (el downgrade no toca los índices GIN de búsqueda de products:
    #  los gestiona la migración 26a56be90086)
    op.drop_index(op.f('ix_payment_events_payment_id'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_payments_provider_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
